# .github/workflows/manual-release.yml
name: Manual Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Publish dry-run? (true/false)'
        required: true
        default: 'true'

jobs:
  release:
    name: 🚀 Release package
    runs-on: ubuntu-latest

    steps:
      # 1. haal de code en de volledige git-geschiedenis op
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. zorg dat Node.js klaarstaat
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      # 3. installeer deps
      - name: Install dependencies
        run: npm ci

      # 4. Versie nummer lezen
      - name: Get version
        id: get_version
        run: echo "::set-output name=VER::$(node -p "require('./package.json').version")"

      # 5. commit de bijgewerkte package.json en maak een tag
      - name: Create & push tag
        run: |
          V=${{ steps.get_version.outputs.VER }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v$V" -m "Release v$V"
          git push origin "v$V"

      # 6. publiceer naar npm 
      - name: Publish to npm
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "=== DRY RUN: npm publish --dry-run ==="
            npm publish --dry-run --access public
          else
            echo "=== REAL PUBLISH: npm publish ==="
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
